#### This script reads input generated by install_pkgs_R.sh as a file 
#### with a column of all packages needing installation and install them 

# Clean workspace 
rm(list=ls())

# Environment variables
args=commnandArgs(trailingOnly=TRUE)

# Set library paths -- modified as needed --
#new_path=paste("/castor/project/home/mararc/bin/R/",version$major,".",version$minor,sep="")
new_path=args[1]
.libPaths(new=new_path)

# Install bioconductor -- modify version as needed --
if(!requireNamespace("BiocManager", quietly=TRUE)) {install.packages("BiocManager"); BiocManager::install(version="3.11")}

# Install devtools
if(!requireNamespace("devtools", quietly=TRUE)) {install.packages("devtools")}

# Read package list
pkgs<-read.table("tmp_pkgs", quote="", header=FALSE, stringsAsFactors=FALSE)

# Install
for(i in 1:nrow(pkgs)) {
	cat(" #### INSTALLING ",pkgs[i,]," ####\n")
	if(! require(pkgs[i,])) {install.packages(pkgs[i,], dependencies=TRUE)}
	cat("#### FINISHED ",pkgs[i,]," ####\n")
	}

cat("#### DONE ####\n")
SessionInfo()	
